default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deriv_docs_app
  password: DerivDocs123
  host: localhost

development:
  <<: *default
  database: deriv_docs_app_development

test:
  <<: *default
  database: deriv_docs_app_test

production:
  <<: *default
  database: deriv_docs_app_production
  username: deriv_docs_app
  password: <%= ENV['DERIV_DOCS_APP_DATABASE_PASSWORD'] %>
